### ISSUE TITLE
一覧系データテーブル表示調整

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#132]
一覧系データテーブル（MUI DataGrid）の表示形式を調整する

- [ ] 1. 各カラムの表示幅の自動調整
  - 現在時点（8/3w）の実装では、各データテーブル（Workspaces, AccountManager, ..）のカラム幅は固定されており（minWidth）、ブラウザの幅が変更されると、表示が切れてしまうケースがある。
  - 参考として、Workspaces→Recordsの画面のデータテーブルは、カラム幅はある程度自動調整されるようになっており、これと類似した動作とすることを想定。 （※ただしRecordsのデータテーブルは、MUI DataGridは使用されていない）
  - 対象画面
    - Workspaces
    - Account Manaer

**Comment by hunghongnam** [comment]
Điều chỉnh dạng hiển thị của table data(MUI DataGrid)

1. Tự động điều chỉnh độ rộng hiển thị của các column
- Trong cách triển khai hiện tại (8/3w), độ rộng cột của mỗi bảng dữ liệu (Workspaces, AccountManager, ..) là cố định (minWidth) và có trường hợp phần hiển thị bị cắt khi độ rộng của trình duyệt thay đổi. 
- Để tham khảo, bảng dữ liệu trên màn hình Workspaces → Records tự động điều chỉnh độ rộng cột ở một mức độ nào đó và giả định rằng nó sẽ hoạt động theo cách tương tự. 
(*Tuy nhiên, MUI DataGrid không được sử dụng cho bảng dữ liệu Records)
- Màn hình đối tượng
Workspaces
Account Manaer
