### ISSUE TITLE
FastAPIアプリケーションのログファイル出力

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#134]
### 対応内容

- FastAPIアプリケーション（BackEnd）で出力されているログを、ファイル保存できるようにする。

- 詳細
  - loggingの設定は設定ファイルで定義する（studio/conf/logging.yaml）
  - loggingのデフォルト設定はコンソール出力としておく
  - loggingのファイル出力設定は以下を想定
    - TimeRotatingFileHandler を利用想定、日次のローテーション
    - ログの出力先は studio/logs/app*
    - （可能であれば）BackEndのコードからも、上記のログファイルへ出力可能とする

**Comment by hunghongnam** [comment]
Nội dung:
- Cho lưu file log export bằng FastAPI application (BackEnd).

- Detail :
  - Định nghĩa setting logging bằng file cài đặt (studio/conf/logging.yaml)
  - Cài đặt default của logging là export console 
  - Cài đặt  export file của logging như dưới
    - Giả sử sử dụng TimeRotatingFileHandler, rotation hàng ngày
    - Đích export của log là studio/logs/app*
    - (Nếu có thể) cho phép export file log ở trên từ cả code Backend

**Comment by itutu-tienday** [comment]
@quanpython 

Please research and address the following issue matters
- https://github.com/arayabrain/optinist-for-server/pull/139/files#r1315304035
