### ISSUE TITLE
redirect関連の調整

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/optinist-for-server#151]
- paginationのクエリパラメータ(`?limit=50&offset=0`)を使用している画面で、ブラウザバックを行うと、2回分のredirectを遡る必要がある
  - Account Manager画面など

- 関連
  - #143

**Comment by hunghongnam** [comment]
- Nếu thực hiện back trình duyệt trên màn hình sử dụng tham số truy vấn pagination (?limit=50&offset=0), sẽ cần truy tìm lại hai phần redirect.
  - Màn hình Account Manager, v.v.
  
-Task Liên quan
 - https://github.com/arayabrain/optinist-for-server/issues/143
