### ISSUE TITLE
3. Database（3-2. Cells）

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#17]

**Comment by reactplus-thom** [comment]
デモ動画：https://drive.google.com/drive/folders/1Gtb9yb6rODIeHnO-AuCUIEUu6XqDbJMT

**Comment by itutu-tienday** [comment]
@reactplus-thom 
念のため確認ですが、レビュー対象のPRは、#50 でOKでしょうか
※ #19 も同様
