### ISSUE TITLE
性能改善（BE API）

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#170]
BackEnd APIについて、性能検証・性能改善を対応する

### テスト条件

- 対象API
  - Public Database API
    - /public/experiments
    - /public/cells

- 対象データ件数
  - experiments: 100件
  - cells: 100,000件（1 experimentsあたり1,000件）

- 性能テストツール
  - apachebench など
    - コマンド例
      - > ab -c xx -n xx "http://127.0.0.1:8000/public/experiments?offset=0&limit=50"

- 動作環境
  - マシンスペック: 2020年頃以降のPC (Core-i7, Mem 8GB 程度)
  - Docker利用（docker-compose.yml or docker-compose-dev.yml ）

- 期待性能
  - 応答性能: 20 - 50 requests/sec

**Comment by itutu-tienday** [comment]
### テスト結果（1回目）

- Note
  - 環境: macbook (2020 intel)
  - apachebench を利用

#### テスト結果

1. `-c 1 -n 10`
    - > ab -c 1 -n 10 "http://127.0.0.1:8000/public/experiments?offset=0&limit=50"
	  - 約 3 requests/sec
2. `-c 10 -n 10`
    - > ab -c 10 -n 10 "http://127.0.0.1:8000/public/experiments?offset=0&limit=50"
   	  - 約 3 requests/sec
3. `-c 100 -n 100`
    - > ab -c 100 -n 100 "http://127.0.0.1:8000/public/experiments?offset=0&limit=50"
    - データ件数によらず（experiments,cells,が0件であっても）、BEアプリケーションでフリーズが発生
    - FastAPI/MySQLの接続周りに問題がある可能性？ （非DBアクセスのAPIでは、フリーズはない模様）

**Comment by hunghongnam** [comment]
Thực hiện xác minh hiệu suất và cải thiện hiệu suất cho API BackEnd.

 điều kiện test
 - đối tượng API
    - Public Database API
       -/public/experiments
       -/public/cells

- Số lượng data mục tiêu
  - experiments: 100
  - cells: 100.000 (mỗi experiments là 1.000 data )
- tool test  hiệu suất
  - apachebench, v.v.
     - Ví dụ command
        - ab -c xx -n xx "http://127.0.0.1:8000/public/experiments?offset=0&limit=50"

- Môi trường hoạt động
  - machine specs: PC từ khoảng năm 2020 (Core-i7, Mem khoảng 8GB)
  - Sử dụng Docker (docker-compose.yml hoặc docker-compose-dev.yml)
  
- Hiệu suất expect
  Hiệu suất phản hồi: 20 - 50 requests/sec

**Comment by hunghongnam** [comment]
Kết quả test (lần 1)
- Notes
  - Môi trường: macbook (intel 2020)
  - Sử dụng apachebench
  
kết quả test
- -c 1 -n 10
ab -c 1 -n 10 "http://127.0.0.1:8000/public/experiments?offset=0&limit=50"
  Khoảng 3 requests/sec
--c 10 -n 10
ab -c 10 -n 10 "http://127.0.0.1:8000/public/experiments?offset=0&limit=50"
  Khoảng 3 requests/sec
- -c 100 -n 100
ab -c 100 -n 100 "http://127.0.0.1:8000/public/experiments?offset=0&limit=50"

 - BE application bị treo bất kể số lượng data (ngay cả khi experiments,cells là 0 data )
 - Có thể có vấn đề với kết nối FastAPI/MySQL không? (Dường như không có tình trạng treo với các API không access DB)
→ Như trên, có vấn đề về hiệu suất và sự ổn định khi vận hành nên cần đối ứng

**Comment by itutu-tienday** [comment]
> fastapi-paginationのライブラリは、以下のリンクの count_query 関数を使用してデータ数を計算されいます。
> データのフェッチとデータ数計算の両方の目的で、共通の paginate関数から渡された base queryを使用されます。
> 一方、パフォーマンスを最適化するには、base queryが異なる2つのクエリでデータをフェッチし、データ数を計算する必要があるため、このライブラリは使用できません。
>
> ちなみに、以前、15 requests/sほどかいぜんされたのはfastapi-paginationのライブラリを使用した結果です。
> 使用しなければ、40 requests/sほど改善できると思います。
> https://github.com/uriyyo/fastapi-pagination/blob/8930627ae9110e615c0aec668cd459e979f7752d/fastapi_pagination/ext/sqlalchemy.py#L54

**Comment by itutu-tienday** [comment]
対応済み.

#### 対応結果

- 対応内容
  - DBインデックス調整
  - 一部ライブラリの機能を置換（total件数の集計）
  - DB connection poolsize を調整

- 結果性能
  - 対象の各APIで、以下の性能
    - 15 request/sec 前後
  - また `ab -c 100 -n 100` でBE側が停止しないことを確認
