### ISSUE TITLE
10. Public Database (10-1 Public Experments)

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#18]

**Comment by reactplus-thom** [comment]
・デモ動画：https://drive.google.com/file/d/1qpUVkj8skXQdQbvd2tgzB08KHAeRrNPj/view

**Comment by itutu-tienday** [comment]
暫定で、Dashboard画面に、この画面へのリンクボタンを設置しておいてください。

**Comment by reactplus-thom** [comment]
Tạm thời tại màn hình Dashboard hãy thêm button link để đi đến màn hình này nhé.
