### ISSUE TITLE
4. Workspaces（基本機能）

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#20]
### 対応内容

- 画面UI実装
- APIアクセス実装

**Comment by reactplus-thom** [comment]
・デモ動画：https://drive.google.com/file/d/1P0q30CHWSO6NVjLUoFPgom6iq0T5qkhP/view?usp=drive_link

**Comment by itutu-tienday** [comment]
@reactplus-thom 

- I think the UI is fine and will approve PR #70 
- In this issue, please connect to the API. (workspace API #30  is now available)
