### ISSUE TITLE
Docker構成整備（不具合修正）

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#204]
関連issue (#189) での不具合の修正

- 内容
  - DB(mysql)のバックアップ設定
    - ローテーションの不備（バックアップスクリプト中の変数展開の一部不備）

**Comment by ReiHashimoto** [comment]
開発環境用の以下の内容も追加で対応
- https://github.com/arayabrain/optinist-for-server/pull/215#issuecomment-1764414285
