### ISSUE TITLE
グループ機能追加（BE）

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#209]
Database recordのユーザーへのシェアをグループ単位で設定するための、グループ関連機能の実装

- Design documents
  - Screen
    - https://drive.google.com/drive/folders/13Nd_QW5-1CXKEIl4_sciS9VZvg75opaJ
      - 画面設計（グループ機能）_v1.1.pptx
  - DB
    - https://drive.google.com/drive/folders/1pIHd-EhFAQW0qMziwWZkop0lsW9lrmNf
      - optinist-svr-tables-ddl_v1.1(draft).sql
      - optinist-svr-tables-er_v1.1(draft).svg
  - API
    - https://drive.google.com/drive/folders/1vCyE0B8kMcZZgymXMnVt-_PYMRlHD20a
      - optinist-server-apidoc-v1.1.0(draft).html
      - optinist-svr-api-mock-v1.1.0(draft).zip  (sample code)
  - Authorization
    - https://drive.google.com/drive/folders/1aiezc6vV16cxeLTFwKLaPdTrcYwyv3RQ
      - 権限構成設計_v1.1(draft).xlsx

- 関連
  - #210

**Comment by ReiHashimoto** [comment]
@itutu-tienday グループ管理機能のアクセス権について確認です。

- グループ管理画面は管理者のみ利用可能
- 既存のグループを利用したexperimentの共有設定はadmin, data managerが可能

で合っていますか?
あるいはいずれもadmin, data managerでしょうか。

**Comment by itutu-tienday** [comment]
@ReiHashimoto 
上記、冒頭の仕様の想定です。

・Account Managerの利用権限に同様。
・しかし、現在のFEの実装では、権限が対応されていないようですね。
  → API設計書には権限表の表記がありますが、画面設計書には明記がなかったため、補足しておきます。
  → また、Dashboardのリンク構成も明記がなかったため、補足しておきます。（Dashboard > Adminstrator > Group/Account Manager の様な遷移を想定）

**Comment by ReiHashimoto** [comment]
@itutu-tienday 
資料内に記載ありましたね...失礼しました。
BEのAPIも権限をfixした方が良さそうです。
場合によってはendpointも/group → /admin/groupなどに変更を検討しても良いかもしれません。

**Comment by itutu-tienday** [comment]
@ReiHashimoto 
- 画面設計は、少し説明が簡易なため、既存の権限表資料を更新しておきます。
- API設計は、権限仕様はFixしている想定です。
  - API設計書の「詳細（クリックで展開）」の箇所に記載があります。
  - まだ全チェックしていませんが、現状 権限は考慮してAPI実装されているようです。

- またAPIのURLへのプリフィックス設定は、以前も検討しましたが、実施できるとよいだろうと考えます。
  - ※実施タイミングは要検討。また他のAPI含め全体的にURLを整理必要かもしれない

**Comment by ReiHashimoto** [comment]
@itutu-tienday 
ありがとうございます。

> API設計書の「詳細（クリックで展開）」の箇所に記載があります。
> まだ全チェックしていませんが、現状 権限は考慮してAPI実装されているようです。

確認しました、こちらの仕様で実装されてますね。ありがとうございます。

prefixは一旦保留でOKです。必要な時に再度検討しましょう。
