### ISSUE TITLE
CaImAnバッチ実行環境構築

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#298]
バッチ処理へのCaImAnの導入に伴い、バッチ専用の実行環境（Docker環境）を用意する

- 事前検証
  - [x] Docker container上で、非rootユーザー用のconda環境の構築の検証
    - conda env の create と activate が可能であることを確認
    - 環境には caiman と optinist のパッケージをインストールする
  - [x] caimanの安定稼働の調整・検証
    - メモリ使用量面で、caimanの動作に不安定性がある。  対策を実施
    - 検証条件
      - [x] Workflow画面（GUI）
        - 本番サーバー環境（docker+conda）での稼働
        - offline mode (batch mode) での caiman cnmf実行
        - 本番cnmfパラメータ設定での実行（K=2000など）
      - [x] 解析バッチ処理
        - ※Workflow画面の条件と同様

- 環境構築
  - [x] Docker構成ファイルの整備
    - for production
      - docker-compose.yml
      - Dockerfile
      - ※稼働の安定性などを踏まえ、ファイルの分割を想定
    - for development
      - docker-compose.dev.yml
      - Dockerfile.dev
      - ※稼働の安定性などを踏まえ、ファイルの分割を想定
  - [x] Docker構成に合わせ、dockerコンテナ内での cron 実行スクリプトの更新
    - conda env の activate, 等
  - [x] optinsit(MicroscopeReader) と caiman の同居による .so(libtiff) 競合の解消対応
  - [x] poetry の install 構成の最適化
    - poetry install が重めのため、必須ではない処理の削除など

**Comment by ReiHashimoto** [comment]
> 本番サーバー環境（docker+conda）での稼働

>  現行MATLABプログラムに合わせたcnmfパラメータ設定での実行（K=2000など）

- 本番環境で通常のcaimanをK=2000で実行し、2158secでcnmfの処理自体は進行したことを確認。

> offline mode (batch mode) での caiman cnmf実行

- #305 関連の実装で実行可能になったことを確認
