### ISSUE TITLE
データベース開発環境整備

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#40]
## 対応内容

以下、データベース周りの開発環境整備を行う。

- DB(MySQL)のDockerを追加し、docker-composeで起動するようにする
  - 起動に必要なconfig, Dockerfileなどのファイルは`studio/config/db`に配置する
- MySQLはalembicでPythonによるmigrationを行う想定で構築する
- PythonでDBを扱う際には直接のSQLではなく、SQLALchemyなどのO/R mapperを使用する
  - O/R mapperのschemasは`studio/app/common/models`にテーブルごとのファイルで定義する

まずは、backendからDBへのO/R mapperでのクエリが実行できる状態まで進めたらレビューさせてください。
（さらに細かい頻度でのレビューもOKです）
想定と合っていない場合の修正の時間を短くしたいので、レビュー時点ではusersテーブルだけで良いです。

**Comment by reactplus-thom** [comment]
Trước khi thực hiện code API, nhờ các bạn đối ứng các nội dung dưới đây trước:

- Thêm DB(MySQL) Docker để khởi động bằng docker-compose
-> Các file config, dockerfile cần cho khởi động thì sẽ để ở `studio/config/db`
- Build MySQL bằng cách thực hiện migration trên Python bằng alembic
- Khi thao tác với DB bằng Python thì không sử dụng trực tiếp SQL mà sử dụng O/R mapper như SQLALchemy
- > schemas của O/R mapper sẽ định nghĩa bằng file theo từng table ở `studio/app/common/models`

Trước tiên, nhờ các bạn tiến hành xử lý đến bước đưa về trạng thái để có thể chạy query bằng O/R mapper vào DB từ Backend => xong sau đó báo lại tôi để review cái đã. (Xong một lượt rồi gửi review cũng được, hoặc xong và gửi review từng bước cũng ok nhé)
Để rút ngắn thời gian trong trường hợp phải sửa lại do làm chưa đúng ý, thì quan điểm review ở đây chỉ là bảng users thôi.
