### ISSUE TITLE
ワークフロー処理の中断APIの実装

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#46]
### 対応内容

- 以下issueと同対応内容
  - https://github.com/oist/optinist/issues/511

- 対応内容
  - BE
    - Workflow RUN Cancel API の作成
    - Workflow RUN Cancel 処理の実装（Snakemake）
  - FE
    - Workflow画面のCANCELボタンから、RUN Cancel API の呼び出し
      - 処理の成否はsnackbarでメッセージ表示する

- 補足
  - まずは実現方法を調査・検討、その後 実装へ移る
  - ~対応は optinist (barebone-studio) へ適用し、その後 optinist-for-server へ適用（pull request）する~
    - （追記）barebone-studio と他リポジトリのマージ運用の整理が必要であるため、運用整理までは 当件は optinist-for-server へ直接適用とする

- 関連
  - #99

**Comment by hunghongnam** [comment]
- Giống nội dung đối ứng của issue #511 (https://github.com/oist/optinist/issues/511)

- Nội dung đối ứng 
 Tạo Workflow RUN Cancel API
 Implement xử lý Workflow RUN Cancel （Snakemake）
 Điều chỉnh FrontEnd (Call RUN Cancel API )

- Bổ sung:
 Trước tiên điều tra cách thực hiện, sau đó mới implement.
 Đối ứng apply lên optinist (barebone-studio) , sau đó apply (Pull request ) lên  optinist-for-server

**Comment by hunghongnam** [comment]
@itutu-tienday 
調査状況を共有いたします。
ーーーーーーーーーーーーーーーーーー
現在、実行中の各workflowの PID (Process ID) を記録し、そのPIDに対応するworkflowを停止することができますが、
あるworkflowのPIDを停止すると、実行中の他のworkflowも停止になってしまいます。
この問題について引き続き調査中です。

**Comment by itutu-tienday** [comment]
@hunghongnam 
CC: @ReiHashimoto 
上記、ありがとうございます。

一旦、対応案のイメージ合わせを行いたいと思います。
次回ミーティング時に、上記の詳細（検証コードや実行ログなど）を、確認させていだければと思います。
