### ISSUE TITLE
ミドルウェアバージョンアップ対応（Backend）

### ISSUE THREAD

**Issue by ReiHashimoto** [arayabrain/optinist-for-server#48]
- https://github.com/oist/optinist/issues/531 の一環として以下のミドルウェアのバージョンアップを実施する
  - fastapi, uvicorn, jinja2
- 可能な限り最新版を使用する
  - 特にfastapiについては、最低でも0.93.0以上に上げたい
    - [fastapi-pagination](https://github.com/uriyyo/fastapi-pagination)を使用したいため
    - #42 の実装で、`class Pagination`を作成していますが、今後paginationを使用するAPIが増えそうなので、fastapi-paginationで統一したいです
      - こちらのIssueの対応後に、fastapi-paginationを使用するパターンにFixしていただけますか
- バージョンアップに伴い、必要なコードの修正があれば実施する

**Comment by reactplus-thom** [comment]
- Thực hiện version up middleware, theo 1 phần nội dung của task https://github.com/oist/optinist/issues/531 
fastapi, uvicorn, jinja2
- Sử dụng phiên bản mới nhất trong phạm vi có thể
Đặc biệt về fastapi tối thiểu muốn phải nâng lên 0.93.0 trở lên

-> Vì là muốn sử dụng [fastapi-pagination](https://github.com/uriyyo/fastapi-pagination)
-> Hiện tại đang tạo class Pagination theo đối ứng ở https://github.com/arayabrain/optinist-for-server/pull/42
tuy nhiên tương lai có vẻ như các API sử dụng pagination sẽ tăng lên, vì thế muốn thống nhất bằng fastapi-pagination
=> Sau khi đối ứng issue này, thì nhờ các bạn Fix theo pattern sử dụng fastapi-pagination nhé.
- Khi version up mà cần sửa code thì sẽ thực hiện
