### ISSUE TITLE
Workspace API実装（import/export）

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#53]
### 対応内容

- API実装
  - GET /workspace/export/{id}
  - POST /workspace/import

### 備考

- 以下の関連issueを先行し対応する
  - https://github.com/arayabrain/barebone-studio/issues/38
  - https://github.com/arayabrain/barebone-studio/issues/39

**Comment by ReiHashimoto** [comment]
- https://github.com/arayabrain/barebone-studio/issues/38

**Comment by itutu-tienday** [comment]
当件ですが、以下のUI調整も適用いただいて良いでしょうか。
（赤枠の部分が不要となったため、削除する）

<img width="1385" alt="workspaces-update-ui" src="https://github.com/arayabrain/optinist-for-server/assets/122338895/29153f61-c5be-4c88-b63e-590aa07f93a5">
