### ISSUE TITLE
3. Database - Filter機能実装

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#55]
### 対応内容

Database関連画面のFilter機能を実装

- 補足
  - MUI のコンポーネント（DataGrid等）の標準のフィルタ機能を利用する形でOKだが、以下の機能の実現を希望
    - 複数の条件の指定（AND条件）が可能
    - 条件項目のリスト選択（またはサジェスチョン）の対応

- 関連画面
  - #16 
  - #17 
  - #18 
  - #19

**Comment by reactplus-thom** [comment]
@itutu-tienday 

> 複数の条件の指定（AND条件）が可能

⇒この機能を利用するためには、DataGrid pro（有料）が必要ですが、いかがでしょうか。

> 条件項目のリスト選択（またはサジェスチョン）の対応

⇒ライブライはこの機能をサポートしていないのですが、
標準のフィルタ機能では、入力操作の同時に入力した値に対して画面上に一致している結果が絞り込まれますが、
それではダメでしょうか？

**Comment by itutu-tienday** [comment]
@reactplus-thom 

> ⇒この機能を利用するためには、DataGrid pro（有料）が必要ですが、いかがでしょうか。

Pro版の導入を、検討しようと考えます。
つきましては、トライアル版での組み込みを試していただけますでしょうか。
↓ 評価ライセンスについて
https://mui.com/x/introduction/licensing/#evaluation-trial-licenses

> ⇒ライブライはこの機能をサポートしていないのですが、

以下のページのサンプルで、リスト選択が実装されているようです。
詳細確認いただけますでしょうか。
- https://mui.com/x/react-data-grid/sorting/
  - Country がリスト選択

**Comment by ReiHashimoto** [comment]
@reactplus-thom 

今回、filteringもsort同様にserver-sideでの実装となります。
https://mui.com/x/react-data-grid/filtering/server-side/

これは、pro/community planに関わらず使用できると思いますので、この方針で実装してください。

**Comment by reactplus-thom** [comment]
@itutu-tienday 

> Pro版の導入を、検討しようと考えます。
> つきましては、トライアル版での組み込みを試していただけますでしょうか。

承知しました。

> 以下のページのサンプルで、リスト選択が実装されているようです。
> 詳細確認いただけますでしょうか。
> 
> https://mui.com/x/react-data-grid/sorting/
> Country がリスト選択

上記リンクの内容は確認しましたが、Countryのようなリスト選択は固定的なデータリストですね。
本システムは、フィルタリングする対象データが固定ではないようですので、リスト選択の対応が難しいです。
また、今のフィルタリングする仕組みとして、クライアント側ではなく、データベースにデータを検索するみたいのため、
仮に対応可能な場合でも、APIを追加したりする必要そうでかなり面倒だということです。

上記ご確認のうえ、もう一度ご検討いただけないでしょうか？

**Comment by itutu-tienday** [comment]
@reactplus-thom 
> 上記リンクの内容は確認しましたが、Countryのようなリスト選択は固定的なデータリストですね。

Experimentsの属性情報の詳細は、顧客へ要件確認中でもあるため、まだ仕様調整の可能性はありますが、現状以下の想定です。

- 検索条件のリストは、固定値とする想定。（登録データから動的には生成しない）
- 検索条件のリストを動的（APIなどから取得）とするか、静的（FEで定義を保持）とするかは、まだ確定前ですが、一旦FEで静的に保持する形を想定ください。

**Comment by reactplus-thom** [comment]
@sanglevinh 

Về vụ Filter theo kiểu chọn từ list value, thì ý đồ của khách là thế này:

- Các thuộc tính filter của Experiments dự kiến sẽ là giá trị cố định (chứ ko phải là genarate động từ dữ liệu DB)
- Ngoài ra list dữ liệu là tĩnh hay động thì vẫn chưa chốt nhưng tạm thời phía FE cứ theo hướng là tĩnh để làm.

Các nd trên vẫn đang trao đổi với khách, chưa chốt cụ thể nhưng tình hình là như vậy.

**Comment by reactplus-thom** [comment]
@itutu-tienday 

> Experimentsの属性情報の詳細は、顧客へ要件確認中でもあるため、まだ仕様調整の可能性はありますが、現状以下の想定です。
> 検索条件のリストは、固定値とする想定。（登録データから動的には生成しない）
> 検索条件のリストを動的（APIなどから取得）とするか、静的（FEで定義を保持）とするかは、まだ確定前ですが、一旦FEで静的に保持する形を想定ください。

この対応に関して、「Brain area」を例にして先に実装していますが、
他の項目は値リストを確定した後に対応してもよろしいでしょうか。

**Comment by itutu-tienday** [comment]
@reactplus-thom 
> この対応に関して、「Brain area」を例にして先に実装していますが、
> 他の項目は値リストを確定した後に対応してもよろしいでしょうか。

上記の内容で、問題ございません。

**Comment by itutu-tienday** [comment]
MUI DataGrid に関して、先日Pro版を組み込みいただきましたが、方針の再検討により、リリース当初（2023/9）は Community版（無償版）を採用する方針で、進める形となりました。

つきましては、お手数をおかけしますが、再度 DataGrid をCommunity に切り替えいただきたいと思います。

なおCommunity 版への切り替えに際しては、以下を想定していますが、相違があればお知らせください。
- Community 版への切り替えにより、仕様が変化する箇所は以下
  - FilterのAnd条件が不可となる
- また Community 版とPro版の切り替えは、比較的簡易である（コード修正が軽微）ことを想定していますが、相違があればお知らせください。
