### ISSUE TITLE
3. Database - API組み込み①

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#56]
### 対応内容

- 以下画面へのAPIアクセス組み込み
  - 10-1. Public Experiments
  - 10-2. Public Cells

- その他の類似画面へのAPI組み込みは、後続issueで対応
  - #57

**Comment by reactplus-thom** [comment]
Tích hợp API màn Database

Nội dung đối  ứng:
Tích hợp API cho các màn hình dưới:

10-1. Public Experiments
10-2. Public Cells

Các màn hình khác thì sẽ đối ứng ở issue riêng
