### ISSUE TITLE
Account API実装

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#59]
### 対応内容

- Account Management用の各APIを用意する
- API利用画面は、 6. Account Manager、他
- 基本的には、MRI Analysis Studio で実装されている Account Management 関連APIの移植
  - MRI Analysis Studio ではアカウント情報は基本的にはFirebaseへ保存されているが、それらをRDBへの保存に置き換える。

**Comment by reactplus-thom** [comment]
Nội dung đối ứng:
- Code các API dùng cho Account Management
- Màn hình sử dụng API này là:  6. Account Manager、etc..
- Về cơ bản sẽ là migrate API liên quan Account Management  từ bên pj MRI Analysis Studio
Bên phía MRI Analysis Studio thì thông tin account chủ yếu đang được lưu lên Firebase, vì thế cần thay đổi để lưu sang RDB
