### ISSUE TITLE
公開ページのサンプルページ作成

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#60]
### 対応内容

- 当システム（Optinist for Server）では、ログイン不要の公開ページが存在するが、そのページのサンプル（デザインのフレームなど）を用意しておく
- 上記をBarebone system の段階で組み込んでおく

- 関連
  - #65

**Comment by ReiHashimoto** [comment]
一旦現状の仕様について共有です。

- ログインの要否はパスごとに設定できます
  - https://github.com/arayabrain/optinist-for-server/blob/eef85a762f9007daf3d548be6725b3fa91dd2447/frontend/src/components/Layout/index.tsx#L13
  - ignorePathsで指定されているpathが認証不要の扱いになります
  - 認証不要のページでは、headerやdrawerが表示されません
    - https://github.com/arayabrain/optinist-for-server/blob/eef85a762f9007daf3d548be6725b3fa91dd2447/frontend/src/components/Layout/index.tsx#L53-L60


この仕様のままでもいけそうですが、どうでしょう？

**Comment by itutu-tienday** [comment]
@ReiHashimoto 
一旦、上記の仕様で問題はなさそうかと思います。
※もともと用意されていたということですね

なお 公開ページには、多少のデザインが組み込まれると思われますので、専用のデザインフレームの用意は必要そうです。
上記のデザインフレームのサンプルを、用意いただいてもよいでしょうか？ 
（bareboneで不要そうであれば、for server への直接組み込みでもよいと思います）

**Comment by ReiHashimoto** [comment]
@itutu-tienday 

> 公開ページには、多少のデザインが組み込まれると思われますので、専用のデザインフレームの用意は必要そうです。上記のデザインフレームのサンプルを、用意いただいてもよいでしょうか？

デザインフレーム ≒ AppBar + サイドナビゲーションのイメージでしょうか?
公開ページであればナビゲーションをAppBarに入れても良いかもしれませんね


> （bareboneで不要そうであれば、for server への直接組み込みでもよいと思います）

そうですね、こちらはfor serverへの組み込みとしましょう


一旦、デザインフレームなしでルーティングを調整したものをPR作成しました
- #68

**Comment by itutu-tienday** [comment]
@ReiHashimoto 
> デザインフレーム ≒ AppBar + サイドナビゲーションのイメージでしょうか?

デザインの詳細について、ここまであまり議題に挙がっていませんでしたが、
管理コンソールのデザインには依存しないイメージです。

例）以下の様な、一般的なWEBページのイメージ（ヘッダ/メニュー/フッタ の構成）
http://observatory.brain-map.org/visualcoding/search/overview

**Comment by ReiHashimoto** [comment]
@itutu-tienday 
先程のPRで、以下のようなPublicページ用のLayoutを追加しました。

簡素なものにしているので、デザインや組み込む内容は今後調整しましょう。



![Image](https://github.com/arayabrain/optinist-for-server/assets/42664619/37336b36-6798-48c7-8f2c-5f4cd6d3cdde)
