### ISSUE TITLE
Workflow処理マルチユーザー対応

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#76]
### 対応内容

※基本的なマルチユーザー対応はすでに対応実施されているが、その後確認されている、いくつかの対応必要事項について、対応実施する。

- Snakemake関連
  - [x] snakemake実行設定ファイル（config.yaml (snakemake.yaml)）のマルチユーザー対応
    - https://github.com/arayabrain/barebone-studio/issues/39
    - #119 
- API関連
  - [x] workspace_id の validation
    - 想定仕様）
      1. API I/F の Depends（fastapi） でチェック
          - workspace 存在チェック
          - workspace 権限チェック（他人のデータへの不正アクセス防止）
      2. Standalone mode も考慮（Standaloneの場合は、workspace_id の validationは不要のためskip）

**Comment by ReiHashimoto** [comment]
- inputのディレクトリをworkspace_idごとに分離
