### ISSUE TITLE
5-1. Workflow画面実装（データ選択ダイアログ）

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#77]
### 対応内容

Workflow画面へ、解析対象データの選択ダイアログを組み込む

- 関連
  - #6 
  - #21 
  - #16 
  - #18

**Comment by ReiHashimoto** [comment]
## 仕様案

- TC, TSファイルのパスはexperiment_idによって特定できると仮定

1. データベースビューでカラムを選択し、experiment_idを受け取る
2. experiment_idによってTC, TSファイルそれぞれのパスが決まる
3. これらを1つのリスト内に格納したノードとする
  - 複数画像を受け付けるImageDataNodeの仕組みがベース
  - dictではsnakemakeのinputとして扱えないため、1つのリストに格納し、バックエンドでパターンマッチで識別

**Comment by ReiHashimoto** [comment]
上記案の場合、algoノードの入力が結局ばらけてしまうので、ExpDbData dataclassを作成する
