### ISSUE TITLE
SingInタイムアウト時のリダイレクト処理

### ISSUE THREAD

**Issue by itutu-tienday** [arayabrain/optinist-for-server#98]
SignInがタイムアウトした際、SingIn画面へリダイレクトされる想定だが、現在この機能が動作していない模様。 調査・修正を行う。

#### 事象の詳細

- まずSignInのタイムアウト時間は、 .env の REFRESH_TOKEN_EXPIRE_MINUTES で設定される。
- 上記のタイムアウト時間を超過して認証API（POST /auth/refresh）へアクセスした場合、400エラーが応答される。（※おそらくFirebaseサイドでエラー発生）
- 上記400エラーが返された場合、SingIn画面へ遷移すべきだが、遷移が行われない。

**Comment by ReiHashimoto** [comment]
memo

トークン切れの際の挙動
以下のリクエストが発生しているが、リダイレクトなどはなし

1. GET /users/me→401
    ```
    {"detail":"Token expired, 1691420559 < 1691455427"}
    ```
2. POST /auth/refresh→ 400
    ```
    {detail: "Bad Request"}
    ```

MRIの際に2のパターンでどのようにリダイレクトさせていたか要調査

**Comment by itutu-tienday** [comment]
@ReiHashimoto 
以下、認証トークンの有効期限周りの設計ドキュメントのパスを、共有します。
https://docs.google.com/presentation/d/1n8-qmc2rzsnDzBHHxkssi8l13LFeDtXY/

**Comment by itutu-tienday** [comment]
当issue対応について、おそらくDashboard画面（管理コンソールのTOP画面）について、SingInタイムアウト時のリダイレクト処理が機能していない様であるため、修正対応をお願いします。

- [ ] Dashboard画面（API通信を行っていない画面）へのSingInタイムアウト処理の適用
  - 想定対応案）
    1. Dashboard画面ではAPI通信を行っていないが、API通信を行わずに、適切にTokenの期限チェックが可能であれば、その方式を検討ください。
    2. 1\. の対応が難しい場合は、Dashboard画面でAPI通信を実施してください。（/users/me など）

**Comment by hunghongnam** [comment]
Về issue này, có vẻ chức năng xử lý redirect khi timeout SingIn không hoạt động trên màn hình Dashboard (màn hình TOP của quản lý console), vì vậy cần check và sửa.

 - Xử lý timeout SingIn cho màn hình Darhboard (màn hình không thực hiện call API)
   - Dự kiến đề án đối ứng 
      - Mặc dù việc giao tiếp API không được thực hiện trên màn hình Dashboard nhưng nếu có thể kiểm tra chính xác ngày hết hạn của Token mà không cần giao tiếp API thì hãy áp dụng cách đó.
      - Nếu khó thì vui lòng thực hiện giao tiếp API trên màn hình Dashboard. (access vào /users/me, v.v.)

**Comment by itutu-tienday** [comment]
>  - 想定対応案）
>    - 1\. Dashboard画面ではAPI通信を行っていないが、API通信を行わずに、適切にTokenの期限チェックが可能であれば、その方式を適用してください。
>    - 2\. 1\. の対応が難しい場合は、Dashboard画面でAPI通信を実施してください。（/users/me などへアクセス）

上記の 対応案 2. を採用されたようですが、念のため、1. の対応を不可とした事由を確認させてください。

**Comment by hunghongnam** [comment]
@itutu-tienday 
実際にTokenの期限がいつ切れるかわからないので、Tokenに対してユーザーの干渉は避けられません。
上記に従い、APIを呼び出す方法で実装するのが適切と考えました。
